version: '3.8'

services:
  dashboard-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80"
    environment:
      - VITE_API_BASE_URL=https://api-app.up0fay.easypanel.host
    restart: always
